#!/bin/bash
mapper_name_boot=MAPPER_NAME_BOOT_DUMMY

if [ ! -b /dev/mapper/"$mapper_name_boot" ]; then
  echo "USB key does not seem to be mounted"
  echo "Please make sure you have mounted the USB key using USB_KEY_MOUNT_SCRIPT_DUMMY"

  exit 1
fi

salt-call --local state.apply
