#!/bin/bash
efi_mode=EFI_MODE_DUMMY
usb_key_esp_uuid=USB_KEY_ESP_UUID_DUMMY
usb_key_boot_uuid=USB_KEY_BOOT_UUID_DUMMY
mapper_name_boot=MAPPER_NAME_BOOT_DUMMY

if $efi_mode; then
  echo "Umounting EFI partition"
  umount /boot/efi
fi

echo "Unmounting boot partition"
umount /boot

echo "Closing boot partition"
cryptsetup close /dev/mapper/"$mapper_name_boot"

echo "USB key unmounted successfully"
